keys:
  - &ventus age1mnkz8j9d30e6ttkmft025v6dhetkdpmv6xdh02xzn4lkdpa5h34qn9fcjp
  - &joe-work age1v9n3sruxxjz4erwrggzfu7e60dcljarc7n57sanaukye4zqz53ps58ke8y
creation_rules:
  - path_regex: (hosts|users)\/[\w\/\-\.]*secrets\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *ventus
        - *joe-work